
# This file was generated by msc_to_py.py v0.1.0
# Mixo-Script to Python transpiler
def __MIXO_OP_RESULT__(func, val):
    return func(val)
toInt = lambda x: int(x)
toStr = lambda x: str(x)

with open("./input.txt", 'r', encoding='utf-8') as __MIXO_F__:
	lines = __MIXO_F__.read().split("\n")
nums = list()
nums = list(map(lambda line: __MIXO_OP_RESULT__(toInt, line), lines))
nums = list(map(lambda num: __MIXO_OP_RESULT__(lambda num: num * num, __MIXO_OP_RESULT__(abs, num)), nums))
with open("./output.txt", 'w', encoding='utf-8') as __MIXO_F__:
	__MIXO_F__.write("\n".join(list(map(lambda x: str(x), nums))))
